### ISSUE TITLE
The component works in Android but not iphone when opening the webview in Messenger app

### ISSUE THREAD

**Issue by JerryYuanJ** [adi518/vue-facebook-login#64]
The status is just waiting in iphone, when using it inside a webview of Messenger.

**Comment by adi518** [comment]
To debug this issue, connect your phone in debugging mode to a computer and use Chrome to inspect the webview. You should be able to see errors in the console and that may provide some clue on what went wrong.

**Comment by JerryYuanJ** [comment]
Hi, it seems to be a bug from official and I've built a custom login flow with OAUTH, thanks for replay , I'll close this one.
