### ISSUE TITLE
sdk-locale is beeing ignored

### ISSUE THREAD

**Issue by super-kamil** [adi518/vue-facebook-login#67]
https://jsfiddle.net/rpuk6ghx/1/

`<v-facebook-login app-id="2146252248983683" sdk-locale="pl_PL"></v-facebook-login>`

This should render a polish button but en_US sdk is always loadad.

![image](https://user-images.githubusercontent.com/708028/106467941-98bb8000-649d-11eb-9409-f5dda80ffff0.png)

**Comment by adi518** [comment]
Which version are you on? it's working for me in the latest version.

**Comment by adi518** [comment]
I see what you mean now. The SDK provides a default look and feel, but this component doesn't use that. I can start adding localization for it, but in the meantime users, we will have to their translations through the content slots.

**Comment by super-kamil** [comment]
Thanks for the answer. Do you have an example for this?

**Comment by adi518** [comment]
Honestly, I'm not sure what benefits the locale has. Someone requested it a while ago, so I added it. Go through to the docs "slots" section and you should be able to replace text easily.

**Comment by super-kamil** [comment]
Ok now i understand. Usually you set the locale to change the language (i think). We will try this out. Thx!
