### ISSUE TITLE
Vue Facebook Login Plugin throwing " Expected '(' " error in console

### ISSUE THREAD

**Issue by TheUngroundable** [adi518/vue-facebook-login#70]
When we land on our website using IE 11, we receive this error in console:

<img width="1423" alt="Screenshot 2021-03-12 at 17 42 25" src="https://user-images.githubusercontent.com/35199075/110970833-6b92a500-835a-11eb-92b6-6eb624b64d2a.png">

If i click on that error, i land on this other tab in the developer tools:
<img width="1111" alt="Screenshot 2021-03-12 at 17 42 56" src="https://user-images.githubusercontent.com/35199075/110970871-764d3a00-835a-11eb-9e1f-a0806f396aad.png">

We are using Vue 2 with Vue Facebook Login Component version 4.0.0

**Comment by adi518** [comment]
I had a look and it looks like some vendor generator functions are not being transformed into ES5 (which is required for IE 11 support).

**Comment by adi518** [comment]
Try new version: `4.0.1`.
