### ISSUE TITLE
Everything stopped working even jsfiddle example seems to be broken.

### ISSUE THREAD

**Issue by aceven24** [adi518/vue-facebook-login#75]
Hello,

This component has been working great, but suddenly stopped working with no changes on our end.  I upgraded to the latest package and still have issues.  I then just tried using the plain vanilla in  my code and as well checked out the JSFiddle example and all I get the same issue.  The component just spins and says "please wait".  Prior I was just using the VFBLoginScope component with  no issues, but now the SDK callback never seems to fire.

Thoughts?

**Comment by cage81** [comment]
Same here! It worked until yesterday, today the state is always "working" and the button is unclickable and it shows the "Please wait..." string on it.

**Comment by adi518** [comment]
Look at the console for hints. I'll check out the example.

**Comment by cage81** [comment]
Nothing in the console, I tried to log something in the SdkInit callback but nothing is printed.

**Comment by adi518** [comment]
I'm checking as we speak.

**Comment by TheHandOfKing** [comment]
Same thing is happening here on my side, the button is disabled with 'please wait...'

**Comment by adi518** [comment]
Thus far, I found out `window.fbAsyncInit` doesn't get called. I think it's some sort of issue with the SDK, because once the Facebook SDK script loads, it detects this hook and should run it to initialize the Facebook API.

**Comment by adi518** [comment]
It looks like everything is back to normal. Hard-refresh your apps.
